### PR TITLE
add SVector and MVector constructorof without type params

### PR DESCRIPTION
**Pull request by aplavin**
Vectors are special: they can be constructed without knowing any type parameters, unlike higher-dim arrays.

Only the first added test is actually "new". Others worked before as well, here just making sure they stay fine.

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks. One problem is that this is not true when the argument is a `Vector`. I guess that works currently but it wont after this PR.

**Comment by aplavin** [comment]
It doesn't look like vectors are supported as SArray/MArray arguments anywhere here. Can you elaborate on what exactly "is not true when the argument is a Vector"?

**Comment by aplavin** [comment]
After making this PR, I noticed that I actually need other constructors that accept argument list instead of a tuple as well.
As in, `constructorof(SVector)(1, 2, 3)` (works with this PR) and `constructorof(SVector{3, Int})(1, 2, 3)` (doesn't work). `ConstructionBaseExtras` only defines  `constructorof(SVector{3, Int})((1, 2, 3))` that takes a tuple, unlike original `StaticArrays` constructors that take either of these variants.

This is what I currently have in my code:
```julia
ConstructionBase.constructorof(::Type{SVector}) = SVector
ConstructionBase.constructorof(::Type{<:SVector{S,<:Any}}) where {S} = SVector{S}
```
Is it ok if I add vararg overloads to https://github.com/JuliaObjects/ConstructionBaseExtras.jl/blob/c2145b18830dd207ba5674afeb3db9aadd2f5fd0/src/staticarrays.jl#L7-L8?

**Comment by aplavin** [comment]
CI errors due to some issues with codecov.io setup.

**Comment by rafaqz** [comment]
Yeah I was just thinking about what generally works `SVector` constructor, seems the type is limited to tuple here. 

Also accepting three arguments to replace one is pretty strange thing for constructorof to do. StaticArrays generally has too many constructors, it's a nightmare.

**Comment by aplavin** [comment]
It makes total sense for constructorof to take SArray entries separately. A common usecase is to have a user specified type, and a couple of values to put there:
```julia
struct S
    x
    y
end

vals = (1, 2)

constructorof(S)(vals...) === S(1, 2)  # works as-is
constructorof(SVector)(vals...) === SVector(1, 2)  # would work with this PR
```

This PR in its current state both simplifies the implementation, and supports more inputs - everything supported by SArray constructors. Everything that worked before continues to work, of course.

**Comment by aplavin** [comment]
Anyway, I would understand if you consider this out of scope for this package somehow.

**Comment by rafaqz** [comment]
Yeah this is better, I'm not sure why I felt the need to include `N` and `L` before.

**Comment by aplavin** [comment]
bump...

**Comment by rafaqz** [comment]
Sorry very busy currently. I have to test this against the use cases I wrote the package for.

**Comment by aplavin** [comment]
No hurry for me, anyway.
In case anyone else stumbles across this: even more extensive StaticVectors support is included in the `AccessorsExtra.jl` package ([relevant code](https://gitlab.com/aplavin/AccessorsExtra.jl/-/blob/master/src/AccessorsExtra.jl#L88-103)) along with other packages integrations.

**Comment by aplavin** [comment]
Whoops, sorry, just noticed that the PR got closed. I definitely remember deleting my forks before and PRs remained open - either I did something differently this time, or github has changed.

**Comment by aplavin** [comment]
Anyway, feel totally free to incorporate this fix/improvement.

**Comment by rafaqz** [comment]
Seems it still works anyway, thanks for the PR and sorry it took so long.

**Comment by aplavin** [comment]
Thanks!

I also wonder what's the best way forward to integrate other common packages with ConstructionBase. For example, IntervalSets - they want to remain no-deps and won't add ConstructionBase: https://github.com/JuliaMath/IntervalSets.jl/pull/124.
Do I just make a PR here adding IntervalSets? As I understand, it doesn't make sense to use Requires with such lightweight packages.

**Comment by rafaqz** [comment]
Yeah, perfect place for it. This package is meant to be a grab bag extra packages until we have something better, like first class glue packages.

**Pull request merged**
