### PR TITLE
add IntervalSets support

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Comment by aplavin** [comment]
CI failes due to some codecov setup issues

**Comment by rafaqz** [comment]
Weird. There are some fails on master too after that merge, but only on mac.

**Comment by aplavin** [comment]
pushed a new commit with failfast=false, everything passes on all julia versions and OSes
where did you see the macos failure?

**Comment by rafaqz** [comment]
It may have just been codecov:
https://github.com/JuliaObjects/ConstructionBaseExtras.jl/actions/runs/3266911883/jobs/5371341385#step:7:47

Annoying that codecov can break CI

**Comment by aplavin** [comment]
Not familiar with codecov CI setup, but the new commit should fix any future potential problems with that.

**Comment by rafaqz** [comment]
Haha there is actually an option for that, thanks, TIL

**Comment by rafaqz** [comment]
LGTM

**Comment by aplavin** [comment]
Would you please tag the new version?

**Comment by rafaqz** [comment]
Yeah, nearly did before but the tests hadn't finished yet ;)

**Comment by rafaqz** [comment]
Sent you an admin role request, thanks for contributing

**Pull request merged**
